//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebdocTerminal.Reports {
    
    public partial class OutstandingAmount : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "WebdocTerminal.Reports.OutstandingAmount.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.label3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label3");
            this.label2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label2");
            this.label10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label10");
            this.pivotGrid2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPivotGrid>("pivotGrid2");
            this.fieldDate1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldDate1");
            this.fieldShippingAgent1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldShippingAgent1");
            this.fieldShipperName1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldShipperName1");
            this.fieldClearingAgentName1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldClearingAgentName1");
            this.fieldGDNumber1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldGDNumber1");
            this.fieldNoOfPkgs1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldNoOfPkgs1");
            this.fieldCBM1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldCBM1");
            this.fieldWeight1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldWeight1");
            this.fieldInvoiceNo1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldInvoiceNo1");
            this.fieldTariffHeadExport1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldTariffHeadExport1");
            this.fieldTOTALCBM1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldTOTALCBM1");
            this.fieldVesselName1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldVesselName1");
            this.fieldGrandTotal1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldGrandTotal1");
            this.fieldCashAmount1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldCashAmount1");
            this.fieldbalance1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldbalance1");
            this.fieldInvoiceDate1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldInvoiceDate1");
            this.fieldType1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldType1");
            this.fieldStorageDays1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldStorageDays1");
            this.fieldremoval1 = reportInitializer.GetPivotGridField("pivotGrid2", "fieldremoval1");
            this.pivotGridField1 = reportInitializer.GetPivotGridField("pivotGrid2", "pivotGridField1");
            this.pivotGridField2 = reportInitializer.GetPivotGridField("pivotGrid2", "pivotGridField2");
            this.pictureBox1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox1");

            // Parameters
            this.fromDate = reportInitializer.GetParameter("fromDate");
            this.toDate = reportInitializer.GetParameter("toDate");
            this.Vessel = reportInitializer.GetParameter("Vessel");
            this.voyage = reportInitializer.GetParameter("voyage");
            this.shippingagent = reportInitializer.GetParameter("shippingagent");
            this.clearingAgent = reportInitializer.GetParameter("clearingAgent");
            this.containerNo = reportInitializer.GetParameter("containerNo");
            this.gdNumber = reportInitializer.GetParameter("gdNumber");
            this.CompanyId = reportInitializer.GetParameter("CompanyId");
            this.path = reportInitializer.GetParameter("path");

            // Data Sources
            this.sqlDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource1");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.XRLabel label3;
        private DevExpress.XtraReports.UI.XRLabel label2;
        private DevExpress.XtraReports.UI.XRLabel label10;
        private DevExpress.XtraReports.UI.XRPivotGrid pivotGrid2;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldDate1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldShippingAgent1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldShipperName1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldClearingAgentName1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldGDNumber1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldNoOfPkgs1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldCBM1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldWeight1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldInvoiceNo1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldTariffHeadExport1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldTOTALCBM1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldVesselName1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldGrandTotal1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldCashAmount1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldbalance1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldInvoiceDate1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldType1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldStorageDays1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldremoval1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField pivotGridField1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField pivotGridField2;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
        private DevExpress.XtraReports.Parameters.Parameter fromDate;
        private DevExpress.XtraReports.Parameters.Parameter toDate;
        private DevExpress.XtraReports.Parameters.Parameter Vessel;
        private DevExpress.XtraReports.Parameters.Parameter voyage;
        private DevExpress.XtraReports.Parameters.Parameter shippingagent;
        private DevExpress.XtraReports.Parameters.Parameter clearingAgent;
        private DevExpress.XtraReports.Parameters.Parameter containerNo;
        private DevExpress.XtraReports.Parameters.Parameter gdNumber;
        private DevExpress.XtraReports.Parameters.Parameter CompanyId;
        private DevExpress.XtraReports.Parameters.Parameter path;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox1;
    }
}
