//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebdocTerminal.Reports {
    
    public partial class SoaKerryLogisticsOtherThenPIFFA : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "WebdocTerminal.Reports.SoaKerryLogisticsOtherThenPIFFA.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.label3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label3");
            this.label2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label2");
            this.label10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label10");
            this.pivotGrid1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPivotGrid>("pivotGrid1");
            this.label4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label4");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.fieldInvoiceNo1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldInvoiceNo1");
            this.fieldInvoiceDate1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldInvoiceDate1");
            this.fieldContainerNumber1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldContainerNumber1");
            this.fieldGDNumber1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldGDNumber1");
            this.fieldNoOfPkgs1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldNoOfPkgs1");
            this.fieldClearingAgentName1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldClearingAgentName1");
            this.fieldCBM1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldCBM1");
            this.fieldTariffHeadExport1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldTariffHeadExport1");
            this.fieldTOTALCBM1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldTOTALCBM1");
            this.fieldPerCbm1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldPerCbm1");
            this.fieldPerGD1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldPerGD1");
            this.fieldTOTALRefundtoKerry1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldTOTALRefundtoKerry1");
            this.fieldGrandTotal1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldGrandTotal1");
            this.fieldnetvalue1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldnetvalue1");
            this.fieldtax1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldtax1");
            this.fieldTotalAfterTax1 = reportInitializer.GetPivotGridField("pivotGrid1", "fieldTotalAfterTax1");
            this.pictureBox1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox1");

            // Parameters
            this.usercbm = reportInitializer.GetParameter("usercbm");
            this.usergd = reportInitializer.GetParameter("usergd");
            this.fromDate = reportInitializer.GetParameter("fromDate");
            this.toDate = reportInitializer.GetParameter("toDate");
            this.year = reportInitializer.GetParameter("year");
            this.month = reportInitializer.GetParameter("month");
            this.shippingagent = reportInitializer.GetParameter("shippingagent");
            this.Vessel = reportInitializer.GetParameter("Vessel");
            this.voyage = reportInitializer.GetParameter("voyage");
            this.tax = reportInitializer.GetParameter("tax");
            this.CompanyId = reportInitializer.GetParameter("CompanyId");
            this.path = reportInitializer.GetParameter("path");

            // Data Sources
            this.sqlDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource1");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.XRLabel label3;
        private DevExpress.XtraReports.UI.XRLabel label2;
        private DevExpress.XtraReports.UI.XRLabel label10;
        private DevExpress.XtraReports.UI.XRPivotGrid pivotGrid1;
        private DevExpress.XtraReports.UI.XRLabel label4;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldInvoiceNo1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldInvoiceDate1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldContainerNumber1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldGDNumber1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldNoOfPkgs1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldClearingAgentName1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldCBM1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldTariffHeadExport1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldTOTALCBM1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldPerCbm1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldPerGD1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldTOTALRefundtoKerry1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldGrandTotal1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldnetvalue1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldtax1;
        private DevExpress.XtraReports.UI.PivotGrid.XRPivotGridField fieldTotalAfterTax1;
        private DevExpress.XtraReports.Parameters.Parameter usercbm;
        private DevExpress.XtraReports.Parameters.Parameter usergd;
        private DevExpress.XtraReports.Parameters.Parameter fromDate;
        private DevExpress.XtraReports.Parameters.Parameter toDate;
        private DevExpress.XtraReports.Parameters.Parameter year;
        private DevExpress.XtraReports.Parameters.Parameter month;
        private DevExpress.XtraReports.Parameters.Parameter shippingagent;
        private DevExpress.XtraReports.Parameters.Parameter Vessel;
        private DevExpress.XtraReports.Parameters.Parameter voyage;
        private DevExpress.XtraReports.Parameters.Parameter tax;
        private DevExpress.XtraReports.Parameters.Parameter CompanyId;
        private DevExpress.XtraReports.Parameters.Parameter path;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox1;
    }
}
